### ISSUE TITLE
Requirement of documentation

### ISSUE THREAD

**Issue by imabp** [The-Lazy-People/the-lazy-people.github.io#1]
The repository is lacking in documentation purpose.

**Comment by imabp** [comment]
Preview the updated documentation at: https://github.com/imabp/the-lazy-people.github.io
before merging the pull request.

**Comment by abhishek-yadav-aps** [comment]
thanks for documentation.

**Comment by imabp** [comment]
@abhishekyadav-aps  Welcome. I see the potential and want to enhance the current UX.

**Comment by abhishek-yadav-aps** [comment]
you are most welcome to contribute.
